### ISSUE TITLE
Add a license.

### ISSUE THREAD

**Issue by ghost** [Zackptg5/Unity#1]

**Comment by Zackptg5** [comment]
Not going to lie, I have no idea which license would be the best suited for this. Any suggestions? GPL or Apache?

**Comment by ghost** [comment]
Use GPLv2 if you want copyleft or Apache if you don't.

https://www.gnu.org/licenses/copyleft.en.html

https://www.youtube.com/watch?v=PaKIZ7gJlRU

**Comment by Zackptg5** [comment]
Chose gnu 2. Thanks!
https://github.com/Zackptg5/Unity/commit/17d02e8ace0b63a7962b6f1ef30705358520e319
